### PR TITLE
added db option

### PR DESCRIPTION
**Pull request by MikeWLloyd**
Database option added. 

Three straightforward changes to accomplish this: 

1. Added optional `-db` / `--database` click variable. 
2. Existing input ingress function is used to parse the optional DB file. 
3. Existing nested comparison loop inner loop was modified to have the inner loop 'reference' dict set as either all other inputs (existing `samps`) or if database, then the DB dataframe. 

Given the nature of this addition, I am not sure if additional test files are needed., etc., but I am happy to add if needed.

### CODE REVIEW

**Comment by j-andrews7** [comment]
If the current tests run, I'm happy with it. I'll try to take a look over the weekend. If all is well, I'll push a new version to pypi.

Thanks for the PR!

**Comment by j-andrews7** [comment]
Do you want to take a crack at adding a test database/test? Current tests run fine, but it'd be nice to have this covered as well.

**Comment by MikeWLloyd** [comment]
I added a simple ingress test against a database file, and a simple scoring re-test with a database df. 

Scoring in the main script is unchanged other than what consitutes the reference df. So, I wasn't sure if I should include the scoring re-test as it is already covered in `test_scoring.py`. I can remove the scoring testing from `test_database.py` if it doesn't make sense to have it there again.

**Comment by j-andrews7** [comment]
Excellent, thanks again!

**Pull request merged**
